export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const REMOVE_USER = 'REMOVE_USER';

export const ACCOUNTS_GET_ALL = 'ACCOUNTS_GET_ALL';
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_GET_ONE = 'ACCOUNT_GET_ONE';
export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_DELETE = 'ACCOUNT_DELETE';
export const ACCOUNT_GET = 'ACCOUNT_GET';

export const CATEGORIES_GET_ALL = 'CATEGORIES_GET_ALL';
export const CATEGORY_CREATE = 'CATEGORY_CREATE';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_GET = 'CATEGORY_GET';

export const TRANSACTIONS_GET_ALL = 'TRANSACTIONS_GET_ALL';
export const TRANSACTION_CREATE = 'TRANSACTION_CREATE';
export const TRANSACTION_UPDATE = 'TRANSACTION_UPDATE';
export const TRANSACTION_DELETE = 'TRANSACTION_DELETE';
export const TRANSACTION_GET = 'TRANSACTION_GET';

export const APP_READY = 'APP_READY';
export const APP_NOT_READY = 'APP_NOT_READY';
